### ISSUE TITLE
Nuget dependencies are outdated.

### ISSUE THREAD

**Issue by Hurlu** [Jetro223/DocXNETCore#2]
Hey ! It looks like Nuget dependencies on the packages are outdated, causing it to cause problems while publishing a project depending on it.

Would you accept to update the project with a new .nuspec that I would send as a pull request on the Nuget galleries ? I don't want to fork your own fork and publish a new nuget package, that would only cause confusion for people that would like to use it later.

On a related note, I saw you removed the nuspec in your last commit. Is there any reason for it ?

Thanks !

**Comment by Jetro223** [comment]
Yes, of course - I'll accept the pull request. Reason for removing nuspec - I have absolutely no idea ;-)

Thanks!

**Comment by Hurlu** [comment]
All right, I'll work on it and send it :)
Thanks to you for your work on this!

**Comment by Hurlu** [comment]
Did the pull request, here are my takeaways on it :

- The .nuspec seems to be partially contained inside the .csproj, hence it's disparition.
- After careful re-reading of the NU1605 errors and some swearing, it looks like the problem wasn't on DocXNetCore side, but runtime.unix.SystemIO.FileSystem.

Guess at least the project is updated  ¯\\_(ツ)_/¯

**Comment by Jetro223** [comment]
Hi - thank you. I've merged the pull request and updated the nuget package.
