### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by blakeja** [Jetro223/DocXNETCore#6]
I made an attempt to put a .png into the header of a document and was not able to get it working.  Is it possible to insert images into a document with this package?

**Comment by Jetro223** [comment]
Yes, it's possible to insert images to a document (thanks @dennishog ). Please check this commit for an example: https://github.com/Jetro223/DocXNETCore/commit/7c4843572239bb0e8c05a77aab043c685a138197

**Comment by blakeja** [comment]
Thanks for getting back.  Unfortunately, I am getting back an exception which boils down to "Unable to load DLL 'gdiplus.dll'".  Have you seen this and if so, do you have a way to rectify this error?

**Comment by blakeja** [comment]
I don't see a way to make this work, it's not clear whether this is a net core issue (I'm on 2.1) or something with docker (using the [latest 1803 image](https://hub.docker.com/r/microsoft/dotnet/)).

I did get this working by creating a .dotx template with the images I needed, which I can then apply using [DocX.ApplyTemplate()](https://github.com/xceedsoftware/DocX/blob/85af727e20e5b1d8cba8127bfa985a6d214c113c/Examples/Samples/Document/DocumentSample.cs#L117).
